on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/ethan-ou/vscode-gift-docs.git"
        SOURCE_BRANCH: "*"
        DESTINATION_REPO: "https://github.com/moocunsw/GIFT_DigitalUplift.git"
        DESTINATION_BRANCH: "*"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
