on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: ${{ secrets.SOURCE_URL }}
        SOURCE_BRANCH: "*"
        DESTINATION_REPO: ${{ secrets.DEST_URL }}
        DESTINATION_BRANCH: "*"
      with:
        args: $SOURCE_REPO $DESTINATION_REPO 
